[pytest]
# Папки с тестами
testpaths = tests

# Паттерн для поиска тестов
python_files = test_*.py

# Паттерн для поиска тестовых классов
python_classes = Test*

# Паттерн для поиска тестовых функций
python_functions = test_*

# Вывод
addopts = -v --tb=short

# Игнорируемые предупреждения
filterwarnings =
    ignore::DeprecationWarning